// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy14J3dLYxNHCcS4YSxF1pToThPEOJrq0',
    appId: '1:2042850395:web:579d9bbc684e94ee23237e',
    messagingSenderId: '2042850395',
    projectId: 'flutter-test-5ebbe',
    authDomain: 'flutter-test-5ebbe.firebaseapp.com',
    storageBucket: 'flutter-test-5ebbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXiYqQaM3-EqZcGgJnSXYCYjt4s6QivQ',
    appId: '1:2042850395:android:183887e3e8c7944b23237e',
    messagingSenderId: '2042850395',
    projectId: 'flutter-test-5ebbe',
    storageBucket: 'flutter-test-5ebbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-D5UHA_eVXhRWurfr8b8EoX7yzNBKo4',
    appId: '1:2042850395:ios:5f816d479dbeb5d923237e',
    messagingSenderId: '2042850395',
    projectId: 'flutter-test-5ebbe',
    storageBucket: 'flutter-test-5ebbe.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi-D5UHA_eVXhRWurfr8b8EoX7yzNBKo4',
    appId: '1:2042850395:ios:5f816d479dbeb5d923237e',
    messagingSenderId: '2042850395',
    projectId: 'flutter-test-5ebbe',
    storageBucket: 'flutter-test-5ebbe.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
